services:
  - type: web
    name: api-flask-gpt
    env: docker
    repo: https://github.com/cavinatto/ProjetoFlask
    branch: En3
    rootDir: APIgpt
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://root:AewvbjDMhIaSGnTYcpDJWtsLwheIxbXN@yamabiko.proxy.rlwy.net:25561/railway
